{% set name = "colcon-package-selection" %}
{% set version = "0.2.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/colcon/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 67a5130b70d0e428755185b3fb667e9b2a2dff9eb5440514cc5d4f2a5593ffc1

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - colcon-core >=0.3.19

test:
  requires:
    - python {{ python_min }}
  imports:
    - {{ name.replace("-", "_") }}

about:
  home: https://github.com/colcon/{{ name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    An extension for colcon-core to select a subset of packages for processing.

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
